[package]
name = "flac-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
md-5 = "0.9.1"
bitwriter = { path = "./bitwriter" }
